# Generated by Django 4.2.5 on 2023-10-16 16:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Analitic_space',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Dataset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('size', models.FloatField()),
                ('cant_null', models.IntegerField()),
                ('cant_repeated', models.IntegerField()),
                ('file', models.FileField(upload_to='Datasets/')),
                ('analitic_space', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analitic.analitic_space')),
            ],
        ),
    ]
